config/routes.rb
Rails.application.routes.draw do
  root to: 'gardens#index'

  resources :gardens do
    resources :plants, only: %i[create]
  end

  resources :plants, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/garden.rb
class Garden < ApplicationRecord
  belongs_to :category # <<-- THIS IS WHAT MAKES THE CODE garden.category WORK
  has_many :plants, dependent: :destroy # garden.plants

  # CATEGORIES = ['zen', 'green', 'imperial']
  # validates :category, inclusion: { in: CATEGORIES }
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden

  validates :name, :image_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: %i[ show edit update destroy ]

  # GET /gardens
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1
  def show
    @plant = Plant.new
  end

  # GET /gardens/new
  def new
    @garden = Garden.new
  end

  # GET /gardens/1/edit
  def edit
  end

  # POST /gardens
  def create
    @garden = Garden.new(garden_params)

    if @garden.save
      redirect_to garden_url(@garden), notice: "Garden was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /gardens/1
  def update
    if @garden.update(garden_params)
      redirect_to garden_url(@garden), notice: "Garden was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /gardens/1
  def destroy
    @garden.destroy!

    redirect_to gardens_url, notice: "Garden was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_garden
    @garden = Garden.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def garden_params
    params.require(:garden).permit(:banner_url, :name, :category_id)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  # GET /gardens/:garden_id/plants/new
  # def new
  #   @plant = Plant.new
  #   @garden = Garden.find(params[:garden_id])
  # end

  # POST /gardens/:garden_id/plants
  def create
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new(plant_params)
    @plant.garden = @garden

    if @plant.save
      redirect_to garden_path(@garden)
    else
      # Next line will render the '/views/plants/new.html.erb'
      # render :new, status: :unprocessable_entity

      # Next line will render the '/views/gardens/show.html.erb'
      render 'gardens/show', status: :unprocessable_entity
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy

    redirect_to garden_path(@plant.garden), notice: 'Plant destroyed!'
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/_form.html.erb
<%= simple_form_for(garden) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs mb-5">
    <%= f.input :banner_url %>
    <%= f.input :name %>
    <div>
    <%= f.association :category %>
    </div>
  </div>

  <div class="form-actions d-flex align-items-center gap-3 justify-content-end">
    <%= link_to 'Cancel', gardens_path %>
    <span>or</span>
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/gardens/_garden.html.erb
<div class="card-product mt-4">
  <img src="<%= garden.banner_url %>" />

  <div class="card-product-infos">
    <h4><%= link_to garden.name, garden_path(garden) %></h4>
    <p>Category: <%= garden.category.name %></p>
    <p>
      <%= link_to garden_path(garden), class: 'btn btn-outline-primary btn-sm' do %>
        <i class="fa-solid fa-circle-info"></i> Details
      <% end %>
    </p>
  </div>
</div>

app/views/gardens/_new_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">New garden</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render 'gardens/form', garden: Garden.new %>
      </div>
    </div>
  </div>
</div>

app/views/gardens/edit.html.erb
<h1>Editing garden</h1>

<%= render "form", garden: @garden %>

<br>

<div>
  <%= link_to "Show this garden", @garden %> |
  <%= link_to "Back to gardens", gardens_path %>
</div>

app/views/gardens/index.html.erb
<h1>Gardens</h1>
<h4 class="text-muted opacity-50 mb-3">You have <%= @gardens.count %> gardens</h4>

<div id="gardens">
  <% @gardens.each do |garden| %>
    <%= render garden %>
  <% end %>
</div>

app/views/gardens/new.html.erb
<h1 class="mb-5">New garden</h1>
<h4 class="text-muted opacity-50 mb-3">Enter your garden details</h4>

<div class="white-card">
  <%= render "form", garden: @garden %>
</div>

app/views/gardens/show.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @garden.banner_url %>)">
  <%= @garden.name %>
</div>

<div class="garden-actions d-flex py-3 gap-2">
  <%= link_to edit_garden_path(@garden), class: 'btn btn-outline-primary btn-sm' do %>
    <i class="fa fa-pencil"></i> Edit this garden
  <% end %>

  <%= button_to @garden, method: :delete, class: 'btn btn-outline-danger btn-sm' do %>
    <i class="fa fa-trash"></i> Delete this garden
  <% end %>
</div>

<div class="row">
  <% @garden.plants.each do |plant| %>
    <div class="col-2 mt-4">
      <div class="card">
        <img src="<%= plant.image_url %>" class="card-img-top" alt="Plant image">
        <div class="card-body">
          <p class="card-text">
            <%= plant.name %>
          </p>
        </div>
      </div>
    </div>
  <% end %>

  <div class="col-3 mt-4">
    <div class="white-card">
      <h5 class="mb-3"><i class="fa fa-plus"></i> Add new plant</h5>

      <%= simple_form_for [@garden, @plant] do |f| %>
        <%= f.input :name, label: false, placeholder: 'Name' %>
        <%= f.input :image_url, label: false, placeholder: 'Image URL' %>
        <%= f.submit 'Add plant', class: 'btn btn-outline-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "gardens_logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto align-items-center">
        <li class="nav-item active">
          <%= link_to "All gardens", gardens_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <button type="button" class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
            <i class="fa fa-plus"></i> New garden
          </button>
        </li>
      </ul>
    </div>
  </div>
</div>

<%= render 'gardens/new_modal' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gardens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render '/layouts/navbar' %>

    <div class="container pt-4">
      <p style="color: green"><%= notice %></p>

      <%= yield %>
    </div>
  </body>
</html>

app/views/plants/create.html.erb
<h1>Plants#create</h1>
<p>Find me in app/views/plants/create.html.erb</p>

app/views/plants/destroy.html.erb
<h1>Plants#destroy</h1>
<p>Find me in app/views/plants/destroy.html.erb</p>

app/views/plants/new.html.erb
<h1>New plant</h1>

<!-- POST /plants (plants_path) -->
<!-- POST /gardens/:id/plants (garden_plants_path) -->
<%= simple_form_for [@garden, @plant] do |f| %>
  <%= f.input :name %>
  <%= f.input :image_url %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>